# build environment
FROM node:12.19-alpine3.10 as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app/package.json
RUN yarn install --silent
RUN npm install @vue/cli@3.7.0 -g

COPY . /app
RUN yarn build

# production environment
FROM nginx:1.19-alpine
COPY --from=build /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
