version: "3.7"

services:
    g2-frontend:
        container_name: g2-frontend
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ".:/app"
            - "/app/node_modules"
        ports:
            - "8080:8080"
